### ISSUE TITLE
issues with ears

### ISSUE THREAD

**Issue by tmm2018** [karoldvl/EARS#9]
i did the following:
- downloaded EARS
- installed python in ubuntu
- downloaded the requirements
- downloaded and installed anaconda x86_64
- added my audio driver
- started the server

i noticed the following:
- whenever I start the audio engine the bokeh server goes down

here's my console log:

¨¨
./run.sh 
INFO:bokeh.server.server:Starting Bokeh server version 0.12.5
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['127.0.0.1:5006']
DEBUG:bokeh.server.tornado:Patterns are:
DEBUG:bokeh.server.tornado:  [('/ears/?',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.doc_handler.DocHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7facc5f0d5f8>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/ws',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.ws.WSHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7facc5f0d5f8>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/autoload.js',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7facc5f0d5f8>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/static/(.*)',
DEBUG:bokeh.server.tornado:    <class 'tornado.web.StaticFileHandler'>,
DEBUG:bokeh.server.tornado:    {'path': '/home/tmm88/Workspace/EARS/ears/static'}),
DEBUG:bokeh.server.tornado:   ('/?',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.root_handler.RootHandler'>,
DEBUG:bokeh.server.tornado:    {'applications': {'/ears': <bokeh.server.application_context.ApplicationContext object at 0x7facc5f0d5f8>},
DEBUG:bokeh.server.tornado:     'prefix': '',
DEBUG:bokeh.server.tornado:     'use_redirect': True}),
DEBUG:bokeh.server.tornado:   ('/static/(.*)',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.static_handler.StaticHandler'>)]
INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/ears']
INFO:bokeh.command.subcommands.serve:Starting Bokeh server with process id: 16708
INFO:audio:Initializing a convolutional neural network model...
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
WARNING:theano.tensor.blas:Using NumPy C-API based implementation for BLAS functions.
DEBUG:audio:Loaded Keras model with weights.
INFO:audio:Priming recording device 5.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tmm88/Workspace/EARS/ears/audio.py", line 122, in start
    ref_power=1e-5, top_db=None)
  File "/home/tmm88/.local/lib/python3.5/site-packages/librosa/core/spectrum.py", line 1073, in perceptual_weighting
    return offset + power_to_db(S, **kwargs)
TypeError: power_to_db() got an unexpected keyword argument 'ref_power'

DEBUG:bokeh.server.tornado:[pid 16708] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 16708]   /ears has 0 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 16708] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 16708]   /ears has 0 sessions with 0 unused
INFO:tornado.access:302 GET / (127.0.0.1) 2.28ms
INFO:tornado.access:200 GET /ears (127.0.0.1) 459.74ms
INFO:bokeh.server.views.ws:WebSocket connection opened
DEBUG:bokeh.server.views.ws:Receiver created for Protocol('1.0')
DEBUG:bokeh.server.views.ws:ServerHandler created for Protocol('1.0')
INFO:bokeh.server.views.ws:ServerConnection created
DEBUG:bokeh.server.session:Sending pull-doc-reply from session '7ALPJ52uRtQHh4TP7ZGI6c5BeviSyJ29qzkZfh1dlZMa'
/home/tmm88/.local/lib/python3.5/site-packages/bokeh/core/json_encoder.py:73: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  if pd and isinstance(obj, pd.tslib.Timestamp):
/home/tmm88/.local/lib/python3.5/site-packages/bokeh/core/json_encoder.py:75: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(type(obj), np.float):
./run.sh: line 3: 16708 Illegal instruction     (core dumped) bokeh serve --allow-websocket-origin=127.0.0.1:5006 ears
¨¨

**Comment by karolpiczak** [comment]
New librosa versions have changed the API, so I will have to update it accordingly. For the time being you can rename the `ref_power` parameter to `ref` for newer versions or stick with the older version. As there were some other issues reported with more recent librosa, I've pinned it to `0.4.2` until I have enough time to revamp the whole EARS project.
